### ISSUE TITLE
Don't understand how to install it

### ISSUE THREAD

**Issue by Flavorounet** [wwwwwwwwwwwwwwwwwwwwwwwwwwwwww/m.io#2]
Hi,

I have a little problem installing your server, in fact, when i've launched the server, i can't play, or can't see it at http://127.0.0.1:5000. Should i build an index.html file to make run the game ? Can someone help me or explain me how to make it possible ? Thank's you very much !

**Comment by Flavorounet** [comment]
Anyone to help me.. ?

**Comment by wwwwwwwwwwwwwwwwwwwwwwwwwwwwww** [comment]
Sorry for the delay, in order to connect to the server you will need to host an HTTP server with the packetAnalyzer extension on it, which will automatically connect to a server running on 127.0.0.1:5000.

**Comment by Committing** [comment]
Hi, what is this packageAnalyzer extension I cannot find it online?

I have the same thing where I've built it on a public facing HTTP server and started the node process on port 500:

```
[root@replaced m.io]# npm run test;

> m.io@0.0.1 test /var/www/replaced/httpdocs/test/m.io
> node tests/test.js

Started GameServer on port 5000

```

Now if I browse to the directory it fails to run

http://DOMAIN.COM:5000/test/m.io/

**Comment by wwwwwwwwwwwwwwwwwwwwwwwwwwwwww** [comment]
Read the packet analyzer script. You need a local HTTP server for it to work. Also, open a new issue instead of commenting on a closed one.

**Comment by gotzathe** [comment]
Open a new issue.
